theme = "catppuccin_mocha"

[editor]
scroll-lines = 1
line-number = "relative"
completion-replace = true
true-color = true
undercurl = true
rulers = [ 100 ]
bufferline = "multiple"
color-modes = true
text-width = 100
popup-border = "all"
end-of-line-diagnostics = "hint"

[editor.cursor-shape]
insert = "bar"

[editor.indent-guides]
render = true
character = "▏"
skip-levels = 1

[editor.inline-diagnostics]
cursor-line = "warning"
other-lines = "warning"

[keys.insert]
j = { k = "normal_mode" }
