theme = "catppuccin_mocha"

[editor]
bufferline = "multiple"
color-modes = true
completion-replace = true
cursorline = true
end-of-line-diagnostics = "hint"
line-number = "relative"
popup-border = "all"
rulers = [ 100 ]
scroll-lines = 1
text-width = 100
true-color = true
undercurl = true

[editor.cursor-shape]
insert = "bar"

[editor.indent-guides]
render = true
character = "▏"
skip-levels = 1

[editor.inline-diagnostics]
cursor-line = "warning"
other-lines = "warning"

[keys.insert]
j = { k = "normal_mode" }
