# Extends the base config from https://github.com/helix-editor/helix/blob/master/languages.toml

[[language]]
name = "markdown"

# Soft-wrap markdown files.
[language.soft-wrap]
enable = true
wrap-at-text-width = true


[[language]]
name = "html"
language-servers = [ "superhtml" ]


[[language]]
name = "javascript"
language-servers = [ "typescript-language-server", "vscode-eslint-language-server" ]
indent = { tab-width = 4, unit = "\t" }
formatter = { command = "npx", args = [ "prettier", "--parser", "typescript" ] }
auto-format = true

[[language]]
name = "jsx"
language-servers = [ "typescript-language-server", "vscode-eslint-language-server" ]
indent = { tab-width = 4, unit = "\t" }
formatter = { command = "npx", args = [ "prettier", "--parser", "typescript" ] }
auto-format = true


[[language]]
name = "typescript"
auto-format = true
formatter = { command = "npx", args = [ "prettier", "--parser", "typescript" ] }
language-servers = ["typescript-language-server", "vscode-eslint-language-server"]

[[language]]
name = "tsx"
auto-format = true
formatter = { command = "npx", args = [ "prettier", "--parser", "typescript" ] }
language-servers = [ "typescript-language-server", "vscode-eslint-language-server" ]

[[language]]
name = "svelte"
indent = { tab-width = 4, unit = "\t" }
formatter = { command = "npx", args = [ "prettier", "--parser", "svelte" ] }
auto-format = true
